name: Python Test

on:
  push:
    branches:
      - main  # Déclencher le workflow lorsque du code est poussé sur la branche main

jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation d'une machine Ubuntu pour l'exécution des tests

    steps:
    - uses: actions/checkout@v2  # Récupération du code du référentiel

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installer les dépendances

    - name: Run tests with pytest
      run: |
        pytest
