name: Python application tests

on:
  push:
    branches:
      - library
  pull_request:
    branches:
      - library

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Spécifiez la version de Python que vous utilisez, par exemple '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt correct

    - name: Run tests with pytest
      run: |
        pytest
